### ISSUE TITLE
[binding] Go binding

### ISSUE THREAD

**Issue by anakrish** [microsoft/regorus#104]
Implement Go binding for Regorus

**Comment by anakrish** [comment]
@unexge Would this be something you are interested in taking on?

**Comment by unexge** [comment]
@anakrish I don't have a previous experience with Go ↔ Rust interop, but I can take a look. I can definitely help with https://github.com/microsoft/regorus/issues/103 though, we used PyO3 in our [previous project](https://github.com/smithy-lang/smithy-rs). We're also using [jni-rs](https://github.com/jni-rs/jni-rs) to expose a tiny wrapper around Regorus to Java at my $daywork, I can also help with that if needed.

**Comment by anakrish** [comment]
@unexge Java and Python bindings would be great additions. I wonder if there is some way to share code between various FFIs.

**Comment by anakrish** [comment]
Fixed by #124
