### ISSUE TITLE
Function to convert serde_json::Value or serde_yaml::Value into regorus::Value

### ISSUE THREAD

**Issue by lquerel** [microsoft/regorus#195]
This type of conversion will likely be very common. I don't think it's possible, with the current `regorus` API, to use `serde-transcode` (or a similar approach) to perform this conversion efficiently. It might be helpful to add a method to perform this type of transformation.

**Comment by anakrish** [comment]
Would [serde_json::from_value](https://docs.rs/serde_json/latest/serde_json/value/fn.from_value.html) and [serde_yaml::from_value](https://docs.rs/serde_yaml/latest/serde_yaml/fn.from_value.html) be sufficient?

```rust
use serde_json::json;

fn main() {
    let j:serde_json::Value = json!({
        "fingerprint": "0xF9BA143B95FF6D82",
        "location": "Menlo Park, CA",
        "Hello": [
            1,
            "Foo"
        ]
    });
    println!("{j:#?}");

    let yaml = "
        - 1
        - [0, 0, 0]
        - {x: 1.0, y: 2.0}
    ";
    let k : serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
    println!("{k:#?}");

    // Convert serde_json::Value to regorus::Value, consuming it.
    let u: regorus::Value = serde_json::from_value(j).unwrap();
    println!("{u:#?}");

    // Convert serde_yaml::Value to regorus::Value, consuming it.
    let v: regorus::Value = serde_yaml::from_value(k).unwrap();
    println!("{v:#?}");
}
```

**Comment by lquerel** [comment]
Sorry, and shame on me, I forgot the basics...

**Comment by anakrish** [comment]
No worries. I'm thinking of adding a `From<serde_json::Value>` to `regorus::Value` since `serde_json::from_value` may not be that intuitive.
