### ISSUE TITLE
Display feature information in documentation

### ISSUE THREAD

**Issue by anakrish** [microsoft/regorus#241]
In the public API for regorus in docs.rs, display that certain API is available only if a specific feature is available.
For example, https://docs.rs/regorus/latest/regorus/struct.Engine.html#method.get_coverage_report does not list that `coverage` feature is necessary for this API.

There has been an attempt to make this work: https://github.com/microsoft/regorus/blob/56bd8841d09120366f5aebd58a12ad84602210d7/Cargo.toml#L165

@mkulke What is the right way to do this?

**Comment by mkulke** [comment]
So, for the time being this relies on nightly and requires additional annotations, not sure if it will work reliably in all cases. stabilization for this doc feature is [[ongoing](https://github.com/rust-lang/rfcs/pull/3631). However, it looks like in the current main the annotation is a bit off, when adjusting it, doc renders ok for that method:

![image](https://github.com/microsoft/regorus/assets/273280/27468b2d-b93f-419e-8428-e5a6542e372b)

![image](https://github.com/microsoft/regorus/assets/273280/2ec9ab08-0976-473e-8472-6c1036a37b92)
