### ISSUE TITLE
Provide a way to obtain policy file names and content from an Engine

### ISSUE THREAD

**Issue by bromls** [microsoft/regorus#254]
To support use cases like policy auditing, it would be helpful if the `Engine` exposed a function that allowed callers to iterate over the mappings of policy file names to policy file content.
An application that uses Rego policies may be run with different policies over time, as the software or configuration is updated, or based on the runtime environment.
For use cases like “[Collaboration using Import](https://www.openpolicyagent.org/docs/latest/faq/#collaboration-using-import)”, the policy Engine supports composition of packages, and accepts multiple policy files.
All of this information is available during Engine creation, as it is input to the `add_policy` and `add_policy_from_file` functions. However, some applications may separate `Engine` creation from where an `Engine` is used to evaluate rules or queries. Therefore, it would be valuable for an `Engine` user to have access to the policy file content.

**Comment by anakrish** [comment]
@bromls How do policies get audited? Do you compute the hash of the policy file contents?
