### ISSUE TITLE
Strings::split incompatibility for empty delimiters

### ISSUE THREAD

**Issue by codido** [microsoft/regorus#291]
OPA and Regorus evaluate split differently when empty delimiters are
used.

In particular, the OPA implementation seems to follow the Go
strings.Split definition ("If sep is empty, Split splits after each
UTF-8 sequence"). In comparison, Regorus uses str::split, which also
returns the beginning and end of the string.

For example:
```
$ opa eval 'split("test", "")'
{
  "result": [
    {
      "expressions": [
        {
          "value": [
            "t",
            "e",
            "s",
            "t"
          ],
          "text": "split(\"test\", \"\")",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

vs.

```
$ regorus eval 'split("test", "")'
{
  "result": [
    {
      "expressions": [
        {
          "value": [
            "",
            "t",
            "e",
            "s",
            "t",
            ""
          ],
          "text": "split(\"test\", \"\")",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

**Comment by anakrish** [comment]
@codido Thanks for reporting this! This scenario is not covered by the OPA test suite and I've added a test locking it down in the Regorus repository.

**Comment by codido** [comment]
@anakrish Thank you!
