### ISSUE TITLE
Add support for converting values to i8

### ISSUE THREAD

**Issue by fitzthum** [microsoft/regorus#324]
This would be handy. I'm not really sure how types work in OPA, though. Maybe this doesn't make sense.

**Comment by anakrish** [comment]
@fitzthum Would [to_number](https://www.openpolicyagent.org/docs/latest/policy-reference/#builtin-conversions-to_number) meet your usecase?

**Comment by fitzthum** [comment]
Hmm let me be slightly less vague. I have a `regorus::Value` that I got from `evaluate_rule` and I want to turn that into an `i8`. So we're talking about outside of Rego rather than in the policy itself (although I might need to figure that out soon).

It's not that hard to convert to `i64` and then to `i8` but it would be handy to skip that step. Btw this is for generating EAR Tokens which have a vector full of `i8`s. In theory other people might want to do this as well.
