### ISSUE TITLE
Question - can I use regorus in a k8s as a sidecar as PDP?

### ISSUE THREAD

**Issue by alvipeo** [microsoft/regorus#349]
Sorry, but I didn't get it from the readme.

Can I use regorus in a k8s as a sidecar as PDP in java and .NET?

**Comment by anakrish** [comment]
@alvipeo, Regorus allows in-process evaluation in many languages including Java and .NET without incurring the overhead of https calls to a sidecar service. You could also build a sidecar container out of it if that fits your use case more.
