### ISSUE TITLE
simplify the regorus API

### ISSUE THREAD

**Issue by eric-therond** [microsoft/regorus#36]
Hello
I am facing troubles integrating regorus into an existing project mainly because of [references](https://github.com/microsoft/regorus/blob/main/src/interpreter.rs#L21) to `modules`/`schedule` in the `interpreter`.

Because of this and the `modules`/`schedule` lifetimes I need to refactor my project to call the regorus API (like in [test cases](https://github.com/microsoft/regorus/blob/main/tests/interpreter/mod.rs#L287)) and then to have a reference to the `interpreter` that is passed through functions of my project that need it (instead of storing the `interpreter` instance into a struct).

What do you think about "to hide" the complexity of the API (create the `Sources`, `Parse` and `Analyze` them, ...) and to store everything (struct instances not references) into the `interpreter`? something like that:
```
let mut interpreter = interpreter::Interpreter::new();
interpreter.add_module("myfile.rego");
interpreter.add_input("foo.json");
interpreter.eval_modules(enable_tracing)?;
```

**Comment by anakrish** [comment]
Great idea. Do you want to take a stab at it?

**Comment by eric-therond** [comment]
I tried a bit and the first part (storing `modules`, `schedule`, `source` objects in the struct interpreter...) requires a lot of changes in the whole code base and it's beyond my skills for the moment.

**Comment by anakrish** [comment]
I've taken a pass at simplifying the API: https://github.com/microsoft/regorus/blob/d69b413c8efe38443ee297295f07f06e5b2e568c/examples/regorus.rs#L14.

Note, there are opportunities for optimizations and refactor/simplification/cleanup. The API will change in future.

**Comment by anakrish** [comment]
@eric-therond 
Can you share your use-case? IIRC you explicitly call eval_rule.

**Comment by eric-therond** [comment]
@anakrish 

1. At the beginning of the program, I parse and "compile" all the rego rules.
2. Then the program evaluates the rego rules (`eval_rule`) that are associated to group of target files (*.yaml => rego(rule1, rule2, rule3), *.json=> rego(rule4, rule5, rule6) ...).
3. In reality it's a bit more complex `eval_rule` can be trigerred depending on some "events".

I suppose I have to do use `eval_query`? I tried in the past, I don't remember why I was not able to continue in this direction. I will try again and update this thread.

**Comment by anakrish** [comment]
Thank you. Do let me know how it turns out. I want to make the Engine API support your use case nicely as well.
