### ISSUE TITLE
Publishing crate to crates.io

### ISSUE THREAD

**Issue by unexge** [microsoft/regorus#64]
Thanks for this amazing crate! I played with it and it looks great! Do you have any plans to publish it to crates.io anytime soon? I'd be happy to help to set up CI for publishing if you want. Thanks!

**Comment by anakrish** [comment]
@unexge Thanks for your interest in the project. Yes, there is a plan to publish to crates.io in Jan 2024. Help in that regard would be highly appreciated!

I'm working on adding more builtins support as well as handling few of the remaining constructs (e.g: `with` keyword) of Rego that I've not handled completely. 

Running `cargo test -r --test opa` will show our current status in regard to the OPA test suite. Though it is not critical that all the builtins are supported for the initial release, we want to get as much done as possible. Help with builtins implementation would also be highly appreciated.

**Comment by anakrish** [comment]
@unexge Do you want to take a stab at publishing the crate?

**Comment by unexge** [comment]
Regorus is on [crates.io](https://crates.io/crates/regorus) now 🎉

**Comment by anakrish** [comment]
Once I added the necessary secrets to the repository, the crate got published as soon as the PRs were merged :)

Thanks for setting this up quickly!

I'm working on documenting the public API now. Will include a few optimizations as well and then publish again.
